### ISSUE TITLE
[Batch Runner] Not able to open batch runner dialog

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#31]
### Problem
Replicate:
- Try to open batch runner dialog, got this error
```
AttributeError: 'QgisInterface' object has no attribute 'legendInterface' 
Traceback (most recent call last):
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/plugin.py", line 971, in show_batch_runner
    dock=self.dock_widget)
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/batch/batch_dialog.py", line 88, in __init__
    self.legend = iface.legendInterface()
AttributeError: 'QgisInterface' object has no attribute 'legendInterface'
```

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/6b599975471f22e7f5f23963684086d97bef3ff9
