### ISSUE TITLE
[Minimum Needs] Python Error when Set Value more than max value

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#37]
### Problem
Reproduce:
- Open `Minimum Needs Manager` tool, and edit one of the resources
- Set the value to more than maximum value
- Python Error is shown, see gif below
![error-more-than-max](https://user-images.githubusercontent.com/1421861/41339316-b52adafa-6f1e-11e8-8379-317d8508dd32.gif)

```
AttributeError: 'ValueOutOfBounds' object has no attribute 'message' 
Traceback (most recent call last):
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_manager_dialog.py", line 604, in save_resource
    parameter.value = float(resource['Default'])
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe_extras/parameters/parameters/numeric_parameter.py", line 157, in value
    self._maximum_allowed_value))
parameters.parameter_exceptions.ValueOutOfBounds: Value (20000.0) must be greater than 0.167 and less than 0.2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_manager_dialog.py", line 607, in save_resource
    'Problem - default value is invalid') + '\n' + e.message
AttributeError: 'ValueOutOfBounds' object has no attribute 'message'
```

In QGIS 2.18 / InaSAFE 4.4, it will give you nice message box:
<img width="1075" alt="screen shot 2018-06-13 at 15 29 20" src="https://user-images.githubusercontent.com/1421861/41339339-c47a8456-6f1e-11e8-8616-0d9be1bc9fe3.png">

**Comment by ismailsunni** [comment]
Just thinking aloud here, perhaps Exception object doesn't have `message` attribute anymore, see the similar error message: https://github.com/north-road/inasafe/issues/18

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/3b6f3d31a1e403f69bef61324e7ffe1555772c0b
