### ISSUE TITLE
[Batch Runner] Can not re-run scenario

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#42]
### Problem
Related to #41 

If I ran the scenario for the second time, I got this warning:
```
2018-06-13T21:26:10     WARNING    Traceback (most recent call last):
              File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/batch/batch_dialog.py", line 866, in read_scenarios
              parser.read(filename)
              File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 697, in read
              self._read(fp, filename)
              File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1080, in _read
              raise MissingSectionHeaderError(fpname, lineno, line)
             configparser.MissingSectionHeaderError: File contains no section headers.
             file: '/Users/ismailsunni/Documents/GISData/InaSAFE/inasafe-5/scenario/batch-report-20180613212537.txt', line: 1
             'InaSAFE Batch Report File\n'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/batch/batch_dialog.py", line 234, in populate_table
              scenarios = read_scenarios(absolute_path)
              File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/batch/batch_dialog.py", line 872, in read_scenarios
              parser.readfp(StringIO(content))
              File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 763, in readfp
              self.read_file(fp, source=filename)
              File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 718, in read_file
              self._read(f, source)
              File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1092, in _read
              fpname, lineno)
             configparser.DuplicateOptionError: While reading from '' [line 5]: option 'p' in section 'batch-report-20180613212537' already exists
```

I can click run all scenario, but only one scenario can run, the other are failed.

If I removed the batch-report-*******.txt, the warning is gone, but I can only run one scenario successfuly.

**Comment by elpaso** [comment]
Fixed in https://github.com/north-road/inasafe/commit/7fa5e9ac618eaeb11259213b0d0dabac7d041729
