### ISSUE TITLE
[GeoNode Upload] Python Error on Uploading Layer

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#43]
### Problem
I tried to upload a layer to geonode, I got this python error
```
2018-06-13T22:10:40     WARNING    Traceback (most recent call last):
              File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/geonode_uploader.py", line 165, in accept
              geonode_session = login_user(url, login, password)
              File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/geonode/upload_layer_requests.py", line 131, in login_user
              match = expression_compiled.search(result.content)
             TypeError: cannot use a string pattern on a bytes-like object
```

I never got this error in InaSAFE 4.4

**Comment by nyalldawson** [comment]
Fixed in https://github.com/inasafe/inasafe/pull/5000/commits/cf61d3145520cfe249787b314b369dd3cbf86469

**Comment by ismailsunni** [comment]
Checked.
